### ISSUE TITLE
Fails to build - however seems there's a fix

### ISSUE THREAD

**Issue by rezzz-dev** [stuartcryan/lastpass-alfred-workflow#17]
Seems that the build does not work with only CLT installed - however seems that there's a fix within this issue possibly: https://github.com/Homebrew/homebrew/issues/46763

Any way to see if this can be merged in as a fix to get it working without have XCode installed?  Thanks!

**Comment by stuartcryan** [comment]
Heya, do you mean the build of the LastPass binary itself? As that would be more the responsibility of the offical project https://github.com/lastpass/lastpass-cli but just want to be sure?

**Comment by rezzz-dev** [comment]
No @stuartcryan -- in that issue link someone made a commit to the lastpass-alfred-workflow makefile in which checks to see XCode or CLT - https://github.com/kalbasit/lastpass-cli/commit/8e960f777f2edefb4e3f8ab331588e1a9c060367

However I see that's more on the lastpass-cli repo  and there's a commit there for it -- my mistake!

However I'm curious as to why when I run brew install lastpass-cli it doesn't pull in the latest lastpass-cli code

**Comment by stuartcryan** [comment]
Heya Rezzz,
That would be as the homebrew code relies on community submissions (as far as I was aware) so there is often a delay between a release and someone making a new brew for it.

Having said that, the latest version 0.7.1 is FINALLY available on HomeBrew, hence I am working on some updates that relied on some features released in that version.
Cheers,
Stuart

**Comment by rezzz-dev** [comment]
:beers: @stuartcryan - I just looked at it this morning and noticed that the newer version was there. Installed and everything is working!
