### ISSUE TITLE
Can't login to LastPass

### ISSUE THREAD

**Issue by gilesbutler** [stuartcryan/lastpass-alfred-workflow#18]
As mentioned in [issue 16](https://github.com/stuartcryan/lastpass-alfred-workflow/issues/16#issuecomment-171794256) - the workflow keeps asking for my vault password over and over again. 

Password has been checked and is correct.

**Comment by stuartcryan** [comment]
All righty :) 
Lets get to the bottom of this one.

In a terminal can you please execute:
`launchctl getenv LPASS_ASKPASS`
copy the value output of that (as that should be a script location). If that is empty then we have a problem (please let me know).

Next just run:
`cat <location from last command>`
Just to make sure that the script is in the right location and we dont have any missing errors. I don't assume we do but hey I like to be thorough (and we need this location for the actual test).

Next run 
`export LPASS_ASKPASS="<locationyougot>" && lpass login <yourloginemail>`

Lets see what the result of that is (it should pop up the applescript login and not the old login). Also can you please run

`which lpass` (just in case yours is in a different location).

Let me know how you go.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
oh also, I wouldn't put it past a special character in your password that may be causing us grief... I am keeping this in mind but if you have any characters including:
' " \ $ that would raise a red flag in my brain as well.

If that is the case perhaps you could prod me in private http://stuartryan.com/contact-me/ (without revealing any more of your password of course). I can then spend some time looking at that.

**Comment by stuartcryan** [comment]
Hmm OK it doesn't seem to be that... just tried with this whopper and it worked OK:
%CF6u[[LvhPu#F-FH"'~`!@#$%^&*()_+-=\][{}|';:"/.,<>?Y_oIQmebyQ60c1~ih>OpDm$dr;T9Kb

**Comment by gilesbutler** [comment]
Hey Stu, sorry for late reply, timezones! I'm currently in Chile.

Ok the output from ```export LPASS_ASKPASS="<locationyougot>" && lpass login <yourloginemail>``` is ```Error: Unable to retrieve password from askpass (no reply)```

It didn't popup anything but I saw outbound connection attempts to LastPass through my network monitor.

When I run ```which lpass``` I get ```/usr/local/bin/lpass```

Thanks

**Comment by stuartcryan** [comment]
Hmm OK,
how about 
`cat <location from last command>`

I am wondering if something in the path is incorrect?
Cheers,
Stuart

**Comment by gilesbutler** [comment]
Ok that outputs:
```
#!/usr/bin/osascript
set my_password to display dialog ¬
    "Please enter your LastPass Vault password:" with title ¬
    "Password" with icon caution ¬
    default answer ¬
    "" buttons {"Cancel", "OK"} default button 2 ¬
    giving up after 295 ¬
    with hidden answer
if length of (text returned of my_password) is not 0 then
    return (text returned of my_password)
else
    display dialog "You didn't enter a password!" buttons ["OK"] default button 1
end if
```

**Comment by stuartcryan** [comment]
Howdy, OK that is good, but puzzling as that definitely means the first command should have worked.

Any chance we could do a screen share (say TeamViewer)? Depending on how long you are out of town for can do it when you get back? Otherwise can work out something with the TimeZones.
Cheers,
Stuart

**Comment by gilesbutler** [comment]
Yep sounds good Stu. I'm back in Sydney in a few days so I'll drop you and email once I'm back up and running.

Cheers!

**Comment by stuartcryan** [comment]
No worries at all, look forward to hearing from you.
Cheers,
Stuart

**Comment by hanoii** [comment]
I am also struggling to login, always asking for my password. I do have 2fa enabled, could that be it?

**Comment by stuartcryan** [comment]
Hi Hanoii and Giles,
Another user seems to have found a temporary work around can you please try this:
https://twitter.com/ianstalk/status/699299474800246784

Cheers,
Stuart

**Comment by gilesbutler** [comment]
Hey @stuartcryan yep that worked for me too :+1: 

Thanks :)

**Comment by stuartcryan** [comment]
Hi Giles,
New code provided by Hanoii, can you please have a go and see if this fixes it for you?
https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.4_beta.alfredworkflow

Cheers,
Stuart

**Comment by gilesbutler** [comment]
:+1: Yep excellent, thanks working now for me @stuartcryan 

Thanks for your help and continuing work on this, really appreciate the time and effort!
