### ISSUE TITLE
Support for 2FA

### ISSUE THREAD

**Issue by hanoii** [stuartcryan/lastpass-alfred-workflow#19]
I don't think 2FA was thought for this integration, I don't even know if it was thought to be handled externally within lastpass-cli. It doesn't look like from a quick review on their code, but I could be mistaken. See lastpass/lastpass-cli#152

Wonder if you thoguht about this? I think this could be related to #18

**Comment by hanoii** [comment]
See answer in the related issue on lastpass-cli, certainly possible it seems.

**Comment by hanoii** [comment]
Well, just add a pull request that did the trick.

**Comment by stuartcryan** [comment]
Hi Hanoii,
Another user seems to have found a temporary work around can you please try this:
https://twitter.com/ianstalk/status/699299474800246784

Cheers,
Stuart

**Comment by hanoii** [comment]
Well, yes, it works, my fix here is simply properly asking for the code.

**Comment by stuartcryan** [comment]
Hi Hanoii,
No worries completely understand. I apologise I missed the notification with the pull request, I can now see it there, will look at getting that into the base code.
Cheers,
Stuart
