### ISSUE TITLE
Does not work although it says „logged in sucessfully“

### ISSUE THREAD

**Issue by kbecker87** [stuartcryan/lastpass-alfred-workflow#2]
Hi! I installed the workflow according to your instructions (Homebrew etc) and when I now try to log in it says it is logged in successfully – but I can’t acces my vault… I do use 2-Factor auth for lastpass, could this be a problem?

![problem](https://cloud.githubusercontent.com/assets/8436596/8766189/39c1cc72-2e2e-11e5-98f6-5178acaf2d7c.png)

**Comment by stuartcryan** [comment]
Hi KBecker87 just wanting to check as you closed this issue that you were able to resolve it?
Kind Regards,
Stuart

**Comment by kbecker87** [comment]
Hi Stuart, thanks for your intrest! I downloaded the Workflow again and after that it worked 😊 Had to be an error somewhere in there… Thanks again for the workflow!

Karl
