### ISSUE TITLE
Update documentation to account for `lpsetemail`

### ISSUE THREAD

**Issue by rootwork** [stuartcryan/lastpass-alfred-workflow#21]
Great work on this!

One small note: The last step of the documentation, and the included video, describe the following--

> Open up the workflow within Alfred, double click the top "Terminal Command" box in the workflow and change "yourloginemail@yourdomain.com" to your LastPass username.

There is no "Terminal Command" box, which initially confused me. But it looks like the `lpsetemail` command has now replaced the need to do that, right?

So just to make it less confusing, that last step should probably be removed, or changed to describe running that command. Not sure if you want to go to the trouble of updating the video too.

**Comment by stuartcryan** [comment]
OOh well picked up!

Thank you for that I will update it in the next release.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
Howdy,
Good news, I have now updated the documentation, apologies for the confusion.

OOH and I always throw this at the end of my support tickets, if you love the workflow, my help etc it would be awesome if at some point you could donate towards getting me some cake and Diet Coke (haha it keeps me programming). Donations of course not required, only if you would like, love the workflow and have the means to do so.

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JM6E65M2GLXHE

Cheers,
Stuart
