### ISSUE TITLE
Copying password fails

### ISSUE THREAD

**Issue by tomkersten** [stuartcryan/lastpass-alfred-workflow#22]
Being completely unfamiliar with Alfred workflows, I'm not really sure how to troubleshoot this...but I am not able to get the password to copy to my paste buffer. The username copies fine (using shift+return), but not the password.

Any thoughts? Or...what can I do to help troubleshoot it?

I have v0.8.1 of the lastpass-cli and Capture::Tiny v0.36 installed.

**Comment by stuartcryan** [comment]
Hi Tom,
Can you please open up a terminal and type the following in order:

lpass ls (you will likely need to log in)
Grab one of the ID numbers then use it to run the following query:

lpass show --password -c 123456789...

Please let me know if that works and the password copies correctly to your clipboard.

Many thanks
Stuart

**Comment by tomkersten** [comment]
Hey, @stuartcryan.

When I run that it _does_ copy fine to my clipboard. Anything else to check?

**Comment by stuartcryan** [comment]
Hmm, OK can you please open up Alfred and go to the workflows tab.

Click through and select the LastPass CLI workflow, in the top right corner click on the little bug icon to enable the debug console.

Please then try to copy a password again and let me know if it outputs any error.

Also just to confirm a few more things:
1. Have you tried with several passwords, just want to make sure?
2. Has this ever worked (i.e. used to work or this is the first time you are using the flow)?
3. How did you install lastpass? (i.e. was it HomeBrew, MacPorts?)
4. Can you please provide the output of "which lpass" on the command line.
5. Do you have the password set to require re-authentication?

I am guessing number 5 might be the issue.

I have been working on a beta build for another ticket, can you please give this a try and see if it helps:
https://dl.dropboxusercontent.com/u/9093155/LastPass%20CLI_1.4.5_beta.alfredworkflow

Cheers,
Stuart

**Comment by tomkersten** [comment]
Great news. After running the Alfred update, it is all working perfectly now. Thanks so much for the response and handy utility. Nice work.

**Comment by stuartcryan** [comment]
Howdy Tom,
Great to hear!
Cheers,
Stuart
