### ISSUE TITLE
lplogin no longer works with 2-factor auth

### ISSUE THREAD

**Issue by AlexPasternak** [stuartcryan/lastpass-alfred-workflow#24]
This workflow worked fine for me in the past when it used to display Terminal window with inputs. Now that it shows dialog box prompts, it's stuck on the 2-factor auth code one. I know I'm putting in the correct code, but it keeps showing the box over and over again. Please fix so that I can login, otherwise it's not very useful obviously :-)

**Comment by stuartcryan** [comment]
Hi Alex,
Can you please advise what form of two factor auth you are using?
Cheers,
Stuart

**Comment by stuartcryan** [comment]
Hi Alex,
Also forgot to ask, can you please advise what version of the CLI interface you have installed.

You can obtain this by running lpass --version in a terminal window.

Kind Regards,
Stuart

**Comment by stuartcryan** [comment]
Hi Alex,
I have just released a new version, can you please check this and see if you are still having issues?
Kind Regards,
Stuart

**Comment by AlexPasternak** [comment]
@stuartcryan, sorry I missed your previous questions, I didn't see the notifications. I updated from:
```
> brew outdated
lastpass-cli (0.7.0 < 0.8.1)
```
Updated and installed new workflow and now I can see my password data. BUT I didn't even get a 2-factor auth prompt, why would that be? Is it because I'm logged in somewhere else on the system? It kind of seemed like 2-factor was actually bypassed.

To answer your other question, I currently have both LastPass Authenticator and Google Authenticator enabled on my account.

**Comment by stuartcryan** [comment]
Hi Alex,
No worries at all. Had you logged in successfully via command line (with lpass login ...) at any point and used 2FA, if you have that would be the reason it remembers you.

If this is not the case, I suggest you log in to your online account and remove all "remembered systems" so you can test just to be sure, otherwise it should ask you to re-auth when the last auth expires.

Please let me know how you go.
Cheers,
Stuart

**Comment by AlexPasternak** [comment]
Oy, I don't know if I want to forget *all* the systems, that would be a pain. Just now it made me lplogin again, but again, master pw only, no code. I also tried explicitly lplogout, same deal. Let's assume it's fixed (lp search is definitely working, unlike before, w00t!), and I'll let you know if I get stuck when the auth expires, as you suggest. Thanks!

**Comment by stuartcryan** [comment]
No worries at all, let me know if you have any further issues.

OOH and I always throw this at the end of my support tickets, if you love the workflow, my help etc it would be awesome if at some point you could donate towards getting me some cake and Diet Coke (haha it keeps me programming). Donations of course not required, only if you would like, love the workflow and have the means to do so.

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JM6E65M2GLXHE

Cheers,
Stuart
