### ISSUE TITLE
Updated LastPass branding icons to latest versions

### ISSUE THREAD

**Issue by stuartcryan** [stuartcryan/lastpass-alfred-workflow#30]
LastPass has upgraded their icon and branding. The workflow needs to be brought back into line with this.

Will double check the original authorisation for using the LastPass IP in the workflow to see if it will carry across, or requires additional authorisation.

**Comment by tconroy** [comment]
Hi @stuartcryan, I opened a PR to update the icon. Thanks for this great workflow!

**Comment by stuartcryan** [comment]
Howdy, thanks so much I will try to get this pushed in this weekend, I have a couple of other things I would like to fix up.

Thanks for coding it up!

**Comment by stuartcryan** [comment]
Awesome... merged in, will be pushing out a new version this weekend :)

**Comment by tconroy** [comment]
Glad to help! Enjoy the weekend. 👍
