### ISSUE TITLE
Feature Request: Display username for matches with more than one entry 

### ISSUE THREAD

**Issue by leopic** [stuartcryan/lastpass-alfred-workflow#31]
First of all, thank you for going through the trouble of doing this, this is awesome.

I often have more than one account per site/service that I use, so the default search results from official client and the Chrome extension are super handy, as they'll display both the site and username, so I can pick the one I'm looking for.

An example

Workflow
<img width="713" alt="screen shot 2016-03-26 at 3 32 42 pm" src="https://cloud.githubusercontent.com/assets/117184/14062302/1d9310b0-f368-11e5-910b-0afb3c1128cb.png">

Native client
<img width="472" alt="screen shot 2016-03-26 at 3 36 45 pm" src="https://cloud.githubusercontent.com/assets/117184/14062318/948f3e3c-f368-11e5-9c2e-9ec56cd16bfc.png">

Chrome extension
<img width="373" alt="screen shot 2016-03-26 at 3 33 04 pm" src="https://cloud.githubusercontent.com/assets/117184/14062303/1d963b8c-f368-11e5-84f4-c22fc5ce39ef.png">

I'll be able to ditch the native client if this happens, yay! Thanks again.

**Comment by stuartcryan** [comment]
Hi Leo,
Sorry for the delay on this, it has been a crazy semester with uni. I will look at GMQ's submission in the next few days (I hope), if all works will pull it into the main branch.
Cheers,
Stuart

**Comment by leopic** [comment]
Don't worry, this was a feature request, not a PR, no need to be sorry.

So glad that @gmq went ahead and did it.

Thank you guys

**Comment by stuartcryan** [comment]
And this has now been merged in... releasing in 3... 2... 1...

Sorry for the delay all, university was extremely intense for me this semester and had to take priority.
