### ISSUE TITLE
Remove password from history

### ISSUE THREAD

**Issue by rralian** [stuartcryan/lastpass-alfred-workflow#35]
Just a quick question because I didn't see this addressed. Is there anything in this that will remove the password from the clipboard history after some amount of time? I'd like to have the ease of working with it, say for a minute or two after copying, but don't necessarily want my password sticking around for long after that.

**Comment by tconroy** [comment]
👍 to this, would also like to see this feature.

**Comment by stuartcryan** [comment]
Howdy,
I have been thinking about this for a while, I believe in the new version of Alfred, I should be able to do this with a new hook in the workflow.

I will see what I can pull together this weekend and see if/how this impacts performance (if it is too much, will provide an option to do so, despite the performance hit).
Cheers,
Stuart

**Comment by stuartcryan** [comment]
All righty, this has been coded, turned out to be pretty painless! To be released very shortly!

**Comment by tconroy** [comment]
awesome, thanks @stuartcryan!
