### ISSUE TITLE
getting the 'master password' window over and over again 

### ISSUE THREAD

**Issue by odedpriva** [stuartcryan/lastpass-alfred-workflow#40]
Hi, 
I'm unable to login ( getting the 'master password' window over and over again ) 

I followed the installation instructions, 

at first I thought it might be related to the MFA ( does the workflow login support MFA with google auth ? ) , but I'm getting the same error even after disabling it. 

This is the result I got when installing the Capture::Tiny, can it be related? 
```
Test Summary Report
-------------------
t/13-stdout-tied.t       (Wstat: 256 Tests: 873 Failed: 1)
  Failed test:  835
  Non-zero exit status: 1
Files=24, Tests=12005, 54 wallclock secs ( 1.61 usr  0.17 sys + 32.52 cusr 20.70 csys = 55.00 CPU)
Result: FAIL
Failed 1/24 test programs. 1/12005 subtests failed.
make: *** [test_dynamic] Error 255
  DAGOLDEN/Capture-Tiny-0.46.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports DAGOLDEN/Capture-Tiny-0.46.tar.gz
Running make install
  make test had returned bad status, won't install without force
```

**Comment by johnolos** [comment]
The alfred-workflow essentially uses the lastpass-cli.

Try login from the terminal manually? I know it remembers your MFA.

**Comment by stuartcryan** [comment]
Hi @odedpriva,
If Tiny::Capture isn't installed, this could definitely result in an issue, can you please try updating homebrew and trying again. Apologies for the delayed response, this truly is best effort when I get some time to sit down and spend time on it.
Cheers,
Stuart

**Comment by odedpriva** [comment]
now it seems to work . 

thanks.

**Comment by stuartcryan** [comment]
Great to hear!
