### ISSUE TITLE
Problem with lastpass-cli installation causing `lpbinary missing` error on El Capitan

### ISSUE THREAD

**Issue by jasalt** [stuartcryan/lastpass-alfred-workflow#43]
I wasn't able to install lastpass-cli as per README.md because of `python2` missing.

Managed to workaround it by symlinking Homebrew installed python2 version sudo ln -s $(which python2) /usr/bin/python2 before running `brew install lastpass-cli --with-pinentry`. The `--with-doc` is seemingly deprecated and script doesn't care about it when it's used.

First I had to disable SIP by booting recovery mode terminal (cmd+r on startup) and running csrutil disable.

Posted issue also on https://github.com/lastpass/lastpass-cli/issues/351

**Comment by stuartcryan** [comment]
Thanks for the heads up. I will keep an eye on that, would prefer it gets resolved in the lastpass-cli tool as that saves having to work around it. 

Appreciate the report!
