### ISSUE TITLE
Weird login behavior on Catalina

### ISSUE THREAD

**Issue by SoPat712** [stuartcryan/lastpass-alfred-workflow#64]
As said in Title, I'm on a Mac on Catalina version 10.15.3 and Alfred version 4.0.9[1142] and I'm having trouble logging in with the extension. 

I ran the command `lpass ls`, and it gave me the right output. I also tried loggin in through the terminal with lpass login myemail@emailprovider.com.

This is debug output when `lplogin is run in alfred`

![image](https://user-images.githubusercontent.com/30350506/82741941-e1734480-9d25-11ea-93e3-31dc986bb451.png)

Not sure how to fix this, any help is appreciated.

**Comment by gberg927** [comment]
#56  and #59 both seem to fix this issue. Definitely worth merging in, but you can manually edit the workflow to include this change.

**Comment by avshyz** [comment]
same issue.

**Comment by nathankoerschner** [comment]
> #56 and #59 both seem to fix this issue. Definitely worth merging in, but you can manually edit the workflow to include this change.

I've been trying this, same setup as OP, no luck (same error message).

**Comment by phaberest** [comment]
Sounds like this repo has been abandoned. 😕

**Comment by premsurya** [comment]
Had the same issue and the fix listed above (#56 or #59 ) helped me solve the issue. Thanks a lot.
